import { filterAdvisors, normalizeFilters, removeFilterChip } from './filtering.js';
import { createProfileDialogController, escapeHtml, isValidMatchScore, renderAdvisorCard, renderProfileContent } from './profiles.js';
import { PRIVATE_STATE_STORAGE_KEY, createPrivateRecord, parsePrivateState, serializePrivateState, writePrivateState } from './private-state.js';

const DATA_URLS = { schools: './data/published/schools.json', advisors: './data/published/advisors.json', tags: './data/published/tags.json' };
const state = { schools: [], advisors: [], tags: [], filters: normalizeFilters(), query: '', sort: 'match', privateState: {}, loadStatus: 'loading' };
const $ = (selector) => document.querySelector(selector);
const profileDialogController = createProfileDialogController($('#profile-dialog'));
const getSchool = (id) => state.schools.find((school) => school.id === id);
const getTag = (id) => state.tags.find((tag) => tag.id === id);
function renderFilters() {
  const openStates = [...document.querySelectorAll('.filter-group, .filter-subgroup')].map((details) => [details.querySelector(':scope > summary')?.textContent, details.open]);
  $('#school-filters').innerHTML = state.schools.map((school) => `<label class="filter-option"><input type="checkbox" data-filter="school" value="${escapeHtml(school.id)}"${state.filters.schools.has(school.id) ? ' checked' : ''}> <span>${escapeHtml(school.name)}</span></label>`).join('');
  const groups = new Map(); state.tags.forEach((tag) => { const key = tag.group || 'other'; if (!groups.has(key)) groups.set(key, []); groups.get(key).push(tag); });
  const groupLabels = { carbon: '碳捕集、利用与封存', energy: '能源与储能', environment: '环境科学与工程', methods: '过程与方法', cross: '交叉学科' };
  $('#tag-filters').innerHTML = [...groups.entries()].map(([group, tags]) => `<details class="filter-subgroup" open><summary>${escapeHtml(groupLabels[group] || '其他方向')}</summary><div class="filter-options">${tags.map((tag) => `<label class="filter-option"><input type="checkbox" data-filter="tag" value="${escapeHtml(tag.id)}"${state.filters.tags.has(tag.id) ? ' checked' : ''}> <span>${escapeHtml(tag.label)}</span></label>`).join('')}</div></details>`).join('');
  [...document.querySelectorAll('.filter-group, .filter-subgroup')].forEach((details) => { const prior = openStates.find(([label]) => label === details.querySelector(':scope > summary')?.textContent); if (prior) details.open = prior[1]; });
  $('#school-count').textContent = state.schools.length; $('#tag-count').textContent = state.tags.length;
}
function visibleAdvisors() { const rows = filterAdvisors(state.advisors, { ...state.filters, query: state.query }, { schools: state.schools, tags: state.tags }); return rows.sort((a, b) => state.sort === 'name' ? String(a.name).localeCompare(String(b.name), 'zh') : state.sort === 'recent' ? String(b.checked_at).localeCompare(String(a.checked_at)) : (isValidMatchScore(b.match_score) ? b.match_score : -Infinity) - (isValidMatchScore(a.match_score) ? a.match_score : -Infinity)); }
function renderResults() {
  if (state.loadStatus !== 'ready') return;
  const rows = visibleAdvisors(); $('#result-count').textContent = `${rows.length} 条`;
  if (!rows.length) { $('#advisor-list').innerHTML = ''; $('#status-region').className = 'status-region empty'; $('#status-region').textContent = '没有符合当前条件的公开档案，请尝试清空筛选或换一个关键词。'; return; }
  $('#status-region').className = 'status-region'; $('#status-region').textContent = '';
  $('#advisor-list').innerHTML = rows.map((advisor) => renderAdvisorCard(advisor, getSchool(advisor.school_id))).join('');
  document.querySelectorAll('[data-profile]').forEach((button) => button.addEventListener('click', () => openProfile(button.dataset.profile, button)));
}
function renderActiveFilters(focusIndex = null) { const labels = [...state.filters.schools].map((id) => ['school', id, getSchool(id)?.name]).concat([...state.filters.tags].map((id) => ['tag', id, getTag(id)?.label])); $('#active-filters').innerHTML = labels.map(([group, id, label]) => `<span class="filter-chip">${escapeHtml(label || id)} <button type="button" data-remove-group="${group}" data-remove="${escapeHtml(id)}" aria-label="移除${escapeHtml(label || id)}">×</button></span>`).join(''); document.querySelectorAll('[data-remove]').forEach((button) => button.addEventListener('click', () => { const buttons = [...document.querySelectorAll('[data-remove]')]; const index = buttons.indexOf(button); state.filters = removeFilterChip(state.filters, button.dataset.removeGroup, button.dataset.remove); const input = document.querySelector(`[data-filter="${button.dataset.removeGroup === 'school' ? 'school' : 'tag'}"][value="${CSS.escape(button.dataset.remove)}"]`); if (input) input.checked = false; renderActiveFilters(index); renderResults(); })); if (focusIndex !== null) { const buttons = document.querySelectorAll('[data-remove]'); const target = buttons[Math.min(focusIndex, buttons.length - 1)] || document.querySelector('#clear-filters'); target?.focus(); } }
function resizePrivateNote(textarea) { if (!textarea) return; textarea.style.height = 'auto'; textarea.style.height = `${Math.max(textarea.scrollHeight, 70)}px`; }
function openProfile(id, trigger) { const advisor = state.advisors.find((item) => item.id === id); if (!advisor) return; const school = getSchool(advisor.school_id); const privateRecord = state.privateState[id] || createPrivateRecord(); $('#profile-content').innerHTML = renderProfileContent(advisor, school, privateRecord); $('#contact-status').value = privateRecord.contact_status; $('#contact-status').addEventListener('change', (event) => savePrivate(id, { contact_status: event.target.value, favorite: event.target.value === '已收藏' })); const note = $('#private-note'); note.addEventListener('input', (event) => { resizePrivateNote(event.target); savePrivate(id, { note: event.target.value }); }); resizePrivateNote(note); profileDialogController.open(trigger); if (typeof requestAnimationFrame === 'function') requestAnimationFrame(() => resizePrivateNote($('#private-note'))); }
function savePrivate(id, patch) { const previous = state.privateState; const next = { ...previous, [id]: createPrivateRecord({ ...(previous[id] || {}), ...patch, updated_at: new Date().toISOString() }) }; const result = writePrivateState(getPrivateStorage(), PRIVATE_STATE_STORAGE_KEY, next); if (!result.ok) { showPrivateMessage('保存失败：浏览器存储空间不可用。', true); return false; } state.privateState = next; renderProgress(); return true; }
function renderProgress() { const records = Object.values(state.privateState); $('#favorite-total').textContent = records.filter((record) => record.contact_status === '已收藏' || record.favorite).length; $('#contact-total').textContent = records.filter((record) => record.contact_status === '已联系').length; }
function showPrivateMessage(message, isError = false) { const className = isError ? ' error' : ''; for (const target of [$('#private-state-message'), $('#private-state-editor-message')]) { if (target) { target.textContent = message; target.className = `${target.id === 'private-state-message' ? 'private-state-message' : 'private-state-editor-message'}${className}`; } } }
function getPrivateStorage() { try { return window.localStorage; } catch { return null; } }
async function importPrivateFile(file) { try { const imported = parsePrivateState(await file.text()); const result = writePrivateState(getPrivateStorage(), PRIVATE_STATE_STORAGE_KEY, imported); if (!result.ok) throw new Error('浏览器存储空间不可用'); state.privateState = imported; renderProgress(); showPrivateMessage(`已导入 ${Object.keys(state.privateState).length} 条私密记录。`); } catch (error) { showPrivateMessage(`导入失败：${error.message}`, true); } }
async function bootstrap() { state.loadStatus = 'loading'; $('#result-count').textContent = '加载中…'; $('#status-region').className = 'status-region'; $('#status-region').textContent = '正在加载公开数据…'; try { const responses = await Promise.all(Object.values(DATA_URLS).map((url) => fetch(url))); if (responses.some((response) => !response.ok)) throw new Error('公开数据读取失败'); const [schools, advisors, tags] = await Promise.all(responses.map((response) => response.json())); if (!Array.isArray(schools) || !Array.isArray(advisors) || !Array.isArray(tags)) throw new Error('数据格式不符合约定'); Object.assign(state, { schools, advisors, tags, loadStatus: 'ready' }); renderFilters(); renderActiveFilters(); renderResults(); } catch (error) { state.loadStatus = 'error'; $('#result-count').textContent = '不可用'; $('#status-region').className = 'status-region error'; $('#status-region').textContent = `公开数据暂时无法加载：${error.message}`; } }
document.addEventListener('change', (event) => { if (event.target.matches('[data-filter]')) { const group = event.target.dataset.filter === 'school' ? state.filters.schools : state.filters.tags; event.target.checked ? group.add(event.target.value) : group.delete(event.target.value); renderActiveFilters(); renderResults(); } if (event.target.id === 'sort-select') { state.sort = event.target.value; renderResults(); } });
$('#search-input').addEventListener('input', (event) => { state.query = event.target.value; renderResults(); }); $('#clear-filters').addEventListener('click', () => { state.filters = normalizeFilters(); renderFilters(); renderActiveFilters(); renderResults(); }); $('#export-state').addEventListener('click', () => { const blob = new Blob([JSON.stringify(serializePrivateState(state.privateState), null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'ccus-private-state.json'; link.click(); URL.revokeObjectURL(link.href); showPrivateMessage('已导出私密状态备份。'); }); $('#import-state').addEventListener('click', () => $('#import-state-file').click()); $('#import-state-file').addEventListener('change', (event) => { const [file] = event.target.files; if (file) importPrivateFile(file); event.target.value = ''; });
function readPrivateState() { try { const raw = localStorage.getItem(PRIVATE_STATE_STORAGE_KEY); if (!raw) return {}; try { return parsePrivateState(raw); } catch { const legacy = JSON.parse(raw); if (!legacy || Array.isArray(legacy) || typeof legacy !== 'object' || legacy.schema_version !== undefined) return {}; return Object.fromEntries(Object.entries(legacy).map(([id, record]) => [id, createPrivateRecord(record)])); } } catch { return {}; } }
state.privateState = readPrivateState(); renderProgress(); bootstrap();
document.addEventListener('click', (event) => { if (event.target.matches('[data-remove]') && !document.querySelector('[data-remove]')) $('#clear-filters')?.focus(); });
